modLoader="javafml"

loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="bioplethora"
version="${file.jarVersion}"
displayName="Bioplethora"
authors="AquTheSeal, Sajevius, Meme Man, SeagullBoi, Sonic-3xn40s"
logoFile="bplogo.png"
description='''
A minecraft mod that adds plenty of new content which mainly focuses on new creatures and terrifying beasts! Varying from small tamable partners, to colossal eldritch demons. All balanced and wonderful!
'''

# Base
[[dependencies.bioplethora]]
	modId="forge"
	mandatory=true
	versionRange="[47,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.bioplethora]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.20.1,1.21)"
	ordering="NONE"
	side="BOTH"

# Dependencies
[[dependencies.bioplethora]]
	modId="geckolib"
	mandatory=true
	versionRange="[4.4.7,)"
	ordering="NONE"
	side="BOTH"